#!/usr/bin/env python3
from optparse import OptionParser
import sys

def main():
	parser = OptionParser(version="%prog 1.0")
	parser.add_option("-i", "--insep", dest="insep",
						type="string", action="store",
						help="input separator",
						default=" ")
	parser.add_option("-o", "--outsep", dest="outsep",
						type="string", action="store",
						help="output separator",
						default=",")
	parser.add_option("-l", "--lastsep", dest="lastsep",
						type="string", action="store",
						help="last output serparator",
						default=";")
	parser.add_option("-s", dest="strip", action="store_true",
						help="strip each input column of whitespace",
						default=False)
	(options, args) = parser.parse_args()

	# parse the arguments
	# read in the file
	lines = sys.stdin.readlines()

	#print(options)
	#print(args)
	for arg in args:
		tmp = [1,1,1]
		orig = arg.split(":")
		tmp[0] = orig[0]
		tmp[1] = (orig[1] if len(orig)>1 else tmp[0] )
		tmp[2] = (orig[2] if len(orig)>2 else 1 )
		for line in lines:
			line = line.strip()
			cols = line.split(options.insep)
			output = ""
			for i in range(int(tmp[0])-1, int(tmp[1]), int(tmp[2])):
				try:
					if(options.strip):
						cols[i] = cols[i].strip()
					output += (cols[i]+str(options.outsep))
				except:
					continue
			output = output.rstrip(options.outsep)
			print(output,end=options.lastsep+'\n')

main()
